name: 'Setup'
description: 'Setup workflow'
inputs:
  javaVersion:
    description: 'Java version'
    required: true
    type: string
    default: '11'
runs:
  using: 'composite'
  steps:
    - name: Set up JDK ${{ inputs.javaVersion }}
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: ${{ inputs.javaVersion }}

    - name: Create .m2 folder
      run: mkdir -p $HOME/.m2

    - name: Copy settings.xml to .m2 folder
      run: cp ./settings.xml $HOME/.m2/settings.xml